language: swift
osx_image: xcode9.2
branches:
  only:
  - develop
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=FreestyleLibreFileDriver.xcodeproj
  - OSX_SCHEME="FreestyleLibreFileDriver"
  matrix:
  - DESTINATION="arch=x86_64" SCHEME="$OSX_SCHEME" RUN_TESTS="YES"

before_script:
- sh scripts/bootstrap

script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- if [ $RUN_TESTS == "YES" ]; then
    xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test;
  else
    xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build;
  fi
- if [ $RUN_TESTS == "YES" ]; then
    xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test;
  else
    xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build;
  fi

