language: swift
osx_image: xcode9.2
script: 
    xcodebuild clean build -project FreestyleLibreFileDriver.xcodeproj -scheme FreestyleLibreFileDriver -sdk macosx -destination arch=x86_64 -configuration Debug ONLY_ACTIVE_ARCH=NO test
